import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head';
import ReduxProvider from "./providers/ReduxProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Webai",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>

                      <link rel="icon" href="/logo.png" />

      </Head>
      <ReduxProvider>
              <body className={"bg-black"}>{children}</body>

      </ReduxProvider>
    </html>
  );
}
