import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Webai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>

                      <link rel="icon" href="/logo.png" />

      </head>
      <body className={"bg-black"}>{children}</body>
    </html>
  );
}
